version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # env_file:
      # - .env.local
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
      - minio

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  worker:
    build:
      context: ./medical-transcription
      dockerfile: Dockerfile.worker
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./medical-transcription/.env.local
    depends_on:
      - redis
      - minio
    volumes:
      - ./medical-transcription/transcription.db:/app/transcription.db

volumes:
  redis_data:
  minio_data:
